language: java
sudo: false
script: mvn clean install -Dmaven.javadoc.skip=true
mvn test -B
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7
  - openjdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - cd java
